name: âœ… libhal Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  lint:
    uses: libhal/libhal/.github/workflows/lint.yml@main
    with:
      library: libarmcortex
    secrets: inherit
  docs:
    uses: libhal/libhal/.github/workflows/docs.yml@main
    with:
      library: libarmcortex
    secrets: inherit
  tests:
    uses: libhal/libhal/.github/workflows/tests.yml@main
    with:
      library: libarmcortex
    secrets: inherit
